Repository faciop-cojt/faciop, pull requests merged in 2020-07, with the labels that each got.

#8 依存関係の解決
  package.json
  yarn.lock
Labels: client sandbox integration, enhancement, ninisan

#13 [WIP] ファイル移動をする
  components/ARFaceViewer/FacemeshVideo.vue
  components/ARFaceViewer/ThreeCanvas.vue
  nuxt.config.js
  plugins/BackgroudCanvas.ts
  plugins/FaceCanvas.ts
  plugins/FacemeshFaceGeometry/face.ts
  plugins/FacemeshFaceGeometry/geometry.ts
  plugins/FacemeshInjectionManager.ts
  plugins/FacemeshProvider.ts
  plugins/FacemeshVideoObject.ts
  plugins/IFaceDataSettable.ts
  plugins/IRenderable.ts
  static/glasses.glb
  tsconfig.json
Labels: client sandbox integration, enhancement, ninisan

#14 AR試着ビューワーコンポーネントの作成
  components/ARFaceViewer/ARFaceViewer.vue
  components/ARFaceViewer/FacemeshVideo.vue
  components/ARFaceViewer/ThreeCanvas.vue
  pages/trying-on.vue
  plugins/FaceCanvas.ts
Labels: enhancement, ninisan

#27 Add metadata about page titles and fix favicon path
  nuxt.config.js
  pages/about.vue
  pages/good.vue
  pages/goods.vue
  pages/index.vue
  pages/upload.vue
Labels: bug, eggplants, enhancement

#28 商品一覧より良く&&不要になったファイル削除
  components/goodsCards.vue
  components/pagination/prev-next.vue
  components/profile.vue
Labels: bug, eggplants, enhancement

#30 Add prev links
  pages/good.vue
  pages/upload.vue
Labels: client-system, eggplants, enhancement

#36 Fix API url
  pages/good.vue
  pages/goods.vue
  pages/upload.vue
Labels: client sandbox integration, eggplants, urgent

#33 [WIP] ファッション内アイテムデータを動的に読み込んで試着できるようにする
  components/ARFaceViewer/ARFaceViewer.vue
  components/ARFaceViewer/FacemeshVideo.vue
  layouts/default.vue
  pages/trying-on.vue
  plugins/FaceCanvas.ts
  plugins/FacemeshVideoObject.ts
  store/FaceViewer.js
Labels: ar-face-viewer, ar-logic, enhancement, ninisan, urgent

#38 ArFaceViewer.vueにファイル名の変更をコミット
  components/ARFaceViewer/ArFaceViewer.vue
  tsconfig.json
Labels: bug, ninisan

#44 Show shopname
  pages/good.vue
Labels: client-system, eggplants, enhancement

#48 arfaceviewerがtryi-on以外で隠れない問題の解決
  components/ARFaceViewer/ArFaceViewer.vue
Labels: ar-face-viewer, ar-logic, bug, ninisan, urgent

#46 見出しとかボタンなど
  layouts/default.vue
  pages/good.vue
  pages/trying-on.vue
  pages/upload.vue
Labels: client-system, eggplants, enhancement
